[package]
name = "haych"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
minify = "1.3.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking"] }
tera = "1.20.0"
toml = "0.8.16"
